# Generated by Django 4.0.6 on 2022-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_url_image_img_remove_news_image_image_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='local_url',
        ),
    ]
