# Generated by Django 4.0.6 on 2022-07-22 11:18

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_image_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_news', to='news.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='local_url',
            field=models.ImageField(default='', upload_to=news.models.news_image_directory_path),
        ),
    ]
