# Generated by Django 4.0.6 on 2022-07-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_image_news_news_image_alter_image_local_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='local_url',
            new_name='image',
        ),
    ]
